services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      POSTGRES_DB: platzi_pay_db
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata: